### ISSUE TITLE
Things To Do for Beta (Survival Update)

### ISSUE THREAD

**Issue by shoghicp** [PocketMine/PocketMine-MP#49]
## Things To Do for Survival Update (Beta)

* [ ] Nether Reactor
* [x] Complete API documentation #50 
* [x] Inventory Management #34 
* [x] Signs #42 
* [x] Tile Entities
* [x] Crafting
* [x] Falling Damage
* [x] Smelting
* [x] Environment damage
* [x] Placing Paintings #28 
* [x] Normal Map Generator #35 
* [x] Entity Moving #32 
* [x] Check for Correct block placement #40 
* [x] Grow Block Updates
* [x] Correct chunk sending #16 
* [x] Better player movement (jerking)
* [x] Individual block properties
* [x] Ban API
* [x] Multiworld Support
* [ ] Portals
* [x] Explosions
* [ ] Mob spawning
* [x] Entity saving
* [x] Snowballs, arrows
* [x] Eating
