### ISSUE TITLE
Main TODO Issue to Alpha_1.0.6

### ISSUE THREAD

**Issue by shoghicp** [PocketMine/PocketMine-MP#54]
## Things To Do for Alpha_1.0.6
- [x] Correct blocks with metadata drop
- [x] Placing blocks where an Entity is #39 
- [x] Doble Doors #53 
- [x] Chat API #51 
- [x] Optional online players broadcast #48 
- [x] Event repetition loop #24 
- [x] More API events #37 
- [x] Player Disconnect memory leak #45 #55 
- [x] Unfreed handlers and events responses memory leak
- [x] Unfreed actions memory leak
- [x] Linux Compile script without root
- [x] Correct entity despawning
- [x] Fall Damage fix
- [x] UPnP Port Forwarding
- [x] Console parameters
- [x] Error dump on server crash
- [x] Added Iron Doors
