### ISSUE TITLE
Things To Do for Alpha_1.1

### ISSUE THREAD

**Issue by shoghicp** [PocketMine/PocketMine-MP#57]
#### 0.6.0 special update
- [x] Placing Signs #42
- [x] New types of blocks
- [x] Armor
- [x] New placement rules for stairs
- [x] New placement rules for slabs
#### Miscellaneous
- [x] Tall grass and flower growth using bonemeal
- [x] Multiple Config Formats class
- [x] ANSI Color Codes support
- [x] Ban API
- [x] Lava and water flow generates cobble, stone and obsidian
- [x] Water now generates source blocks
- [x] Eating
#### Tile Entities
- [x] Tile Entity saving
- [x] Signs
#### Entities
- [x] Entity Gravity #32 
- [x] Entity Saving
- [x] Entity Metadata
- [x] Item Despawn
- [x] Death Messages
- [x] Drowing
- [x] Lava
- [x] Cactus damage
- [x] Fire damage (block)
- [x] Burning
- [x] Suffocation
- [x] Void damage
#### Chunk enhancement #16
- [x] Chunks get corrupted #66 (minor issue, check the info)
#### Anti-cheat
- [x] Inventory check
#### Simple Inventory Support #34
- [x] Checking place
- [x] Partial Saving (only picked blocks)
### Fixed Issues
- [x] Correct time sending #64 #65 
- [x] #62 Division by zero
- [x] Correct lateral slab placement
- [x] Fixed When placing a block in a slab, it becomes a double one (only stone)
- [x] Generated trees now look more normal
- [x] Entities not being deleted
- [x] Item restoration duplication
- [x] Health regeneration during death
