### ISSUE TITLE
MCPE v0.8.0 alpha support TODO

### ISSUE THREAD

**Issue by shoghicp** [PocketMine/PocketMine-MP#938]
### Protocol Update
- [x] Initial Support
- [x] Shift Packet IDs
- [ ] PlayerInputPacket: Used to steer Minecarts
- [x] RotateHeadPacket: New way to send the head/body yaw (for minecarts?)
- [x] MovePlayerPacket: Code the new yaw field
- [x] ContainerSetContentPacket: new pseudo-fields?
- [x] SetTimePacket data change
### Blocks
- [x] Sideway Logs
- [x] Jungle Logs
- [x] Jungle saplings and Jungle tree growth
- [x] All kinds of Wooden Planks
- [x] New Wooden stairs
- [x] New Wooden Slabs/double slabs
- [x] Sponges
- [x] Pumpkins & crafting recipes
- [x] Jack o'Lantern & crafting recipes
- [x] Pumpkin Stem & growth
- [x] Carrots Plant & growth
- [x] Potatoes Plant & growth
- [x] Beetroots Plant & growth
- [x] Cobblestone Walls & crafting recipes
- [x] Cobblestone Walls height handling (like fences)
- [x] Iron Bars & crafting recipes
- [x] Tall Grass, Fern and Dead Bush (placement)
- [x] Hay Bales & crafting recipes
- [x] Coal Block & crafting recipes
- [x] Carpets & crafting recipes
- [ ] Rails, powered rails block & crafting recipes #970
### Items
- [x] Pumpkin Pie & eating it
- [x] Pumpkin Seeds & placement
- [x] Beetroot Soup & crafting
- [x] Beetroot health value
- [x] Clock
- [x] Compass
- [x] Minecart item & crafting
- [x] Redstone dust (no placement)
- [x] Cocoa beans & crafting
### Inventory
- [x] Check hotbar slot update
- [x] Handle new Creative inventory
- [x] Add Shears, Bedrock and Dyes to the creative inventory
- [x] Add cobwebs to the creative inventory
### Entities
- [ ] Breeding?
- [ ] Minecart placement
- [ ] Minecarts
- [ ] Generic entity linking
### Others
- [x] Check new chat formatting
- [x] Check new animations (bonemeal)
- [x] Potatoes, carrots, and beetroot seeds can pop out of grass
- [x] Melon/pumpkin seeds can pop out too?
- [x] Add new maps to TemporalGenerator
### Bugs
- [x] Chests tiles not spawning
- [x] Sign tiles not spawning #964 
- [x] Player heads can't be rotated, but the body rotates
- [x] Time is glitchy
