### ISSUE TITLE
Things To Do for Alpha_1.3

### ISSUE THREAD

**Issue by shoghicp** [PocketMine/PocketMine-MP#98]
#### Permissions & API
- [x] Added 33x33 protected zone around spawn
- [x] Added option to change protection radius
#### New [PMF format](https://github.com/shoghicp/PocketMine-MP/wiki/PMF-Draft)
- [x] Base PMF loading
- [x] Map Type (optimized for sending) #211 
- [x] Plugin Type
- [x] PMF plugin loading
- [x] PMF plugin exporting (using DevTools)
#### Chunks & Multiworld support
- [x] Sending lots of blocks via chunk packets
- [x] Loading multiple worlds at a time
- [x] Dynamic map loading
- [x] Separated gamemode by player
- [x] Scheduled block updates
#### Packet Sending enhancement
- [x] Send buffer
- [x] Better NACK handling
  - Fixes #133, #75, #161 
- [x] After-sent NACK checks
#### Anti-cheat
- [x] Optional item enforcement (no crafting :( )
- [x] Flying in Survival #191
- [x] Creative mode no allowed items
- [x] Noclip
- [x] Moving too fast
#### Inventory Support #34
- [x] Chests & Drop inventory changes
#### Entities
- [x] Fully-functional armor damage reduction #194
- [x] Paintings multiple sizes
#### Tile Entities
- [x] Furnace Inventory #136
- [x] Burning items 
#### Miscellaneous (Fixes & More)
- [x] Selectors
- [x] Query protocol
- [x] RCON protocol
- [x] Usage of @all to select all the players in commands
- [x] Way to display your coordinates
- [x] Cake & Eggs (for MCPE 0.7.0 alpha)
- [x] Buckets (for MCPE 0.7.0 alpha)
- [ ] Better water & lava flowing #209 
- [x] Correct block placing check in block update #40
- [x] Quartz Blocks not getting placed
- [x] Invisible players after death #128 
- [x] Usernames are now checked properly, case-insensitive
- [x] /sudo command
- [x] Damage based on Item on hand
- [x] Sign Posts orientation
- [x] Easier Map importing
- [x] Username completion
- [x] /msg, /tell command
- [x] /me command
- [x] /defaultgamemode command
- [x] New [server.properties](../wiki/server.properties) options
